openapi: "3.0.2"
info:
  title: AI-WEB API
  version: "1.0"
servers:
  - url: http://localhost:5000/api/

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # authentication
  /auth/login:
    $ref: "./routes/auth.yaml#/~1login"
  /auth/logout:
    $ref: "./routes/auth.yaml#/~1logout"

  # user
  /users:
    $ref: "./routes/user.yaml#/~1"
  /users/{user_id}:
    $ref: "./routes/user.yaml#/~1getById"
  /users/delete/{user_id}:
    $ref: "./routes/user.yaml#/~1deleteById"

  # # web project
  # /projects:
  #   $ref: "./routes/webProject.yaml#/~1"
  # /projects/manage:
  #   $ref: "./routes/webProject.yaml#/~1manageUser"
  # /projects/tasks:
  #   $ref: "./routes/webProject.yaml#/~1getTasks"
  # /projects/user/{id}:
  #   $ref: "./routes/webProject.yaml#/~1getByUserId"
  # /projects/{project_id}:
  #   $ref: "./routes/webProject.yaml#/~1getById"
  # /projects/delete/{project_id}:
  #   $ref: "./routes/webProject.yaml#/~1deleteById"

  # # vitals
  # /vitals:
  #   $ref: "./routes/vitals.yaml#/~1getByQuery"
  # /vitals/records:
  #   $ref: "./routes/vitals.yaml#/~1records"
  # /vitals/projects/{id}/medrec:
  #   $ref: "./routes/vitals.yaml#/~1getRecordByProjectId"
  # /vitals/template/{project_id}:
  #   $ref: "./routes/vitals.yaml#/~1getTemplate"
  # /vitals/records/updaterow:
  #   $ref: "./routes/vitals.yaml#/~1updateRecordRow"
  # /vitals/records/deleterow:
  #   $ref: "./routes/vitals.yaml#/~1deleteRecordRow"
  # /vitals/records/deletefile/{id}/medrec:
  #   $ref: "./routes/vitals.yaml#/~1deleteRecord"

  # inference
  /infer/questionnaire:
    $ref: "./routes/infer.yaml#/~1questionnaire"
  /infer/image:
    $ref: "./routes/infer.yaml#/~1image"
  /infer/integrate:
    $ref: "./routes/infer.yaml#/~1integrate"
  /infer/template:
    $ref: "./routes/infer.yaml#/~1getTemplate"

  # report
  /reports:
    $ref: "./routes/report.yaml#/~1update"
  /reports/{report_id}:
    $ref: "./routes/report.yaml#/~1"
  /reports/list:
    $ref: "./routes/report.yaml#/~1getAllReports"
  /reports/image:
    $ref: "./routes/report.yaml#/~1getImage"
  /reports/delete/{report_id}:
    $ref: "./routes/report.yaml#/~1deleteById"
