openapi: "3.0.2"
info:
  title: AI-WEB API
  version: "1.0"
servers:
  - url: http://localhost:5000/api/

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # authentication
  /auth/login:
    $ref: "./routes/auth.yaml#/~1login"
  /auth/logout:
    $ref: "./routes/auth.yaml#/~1logout"

  # user
  /users:
    $ref: "./routes/user.yaml#/~1"
  /users/{user_id}:
    $ref: "./routes/user.yaml#/~1getById"
  /users/delete/{user_id}:
    $ref: "./routes/user.yaml#/~1deleteById"

  # inference
  /infer/questionnaire:
    $ref: "./routes/infer.yaml#/~1questionnaire"
  /infer/image:
    $ref: "./routes/infer.yaml#/~1image"
  /infer/integrate:
    $ref: "./routes/infer.yaml#/~1integrate"
  /infer/template:
    $ref: "./routes/infer.yaml#/~1getTemplate"
  /infer/template/description:
    $ref: "./routes/infer.yaml#/~1getDescription"

  # report
  /reports:
    $ref: "./routes/report.yaml#/~1update"
  /reports/{report_id}:
    $ref: "./routes/report.yaml#/~1"
  /reports/list:
    $ref: "./routes/report.yaml#/~1getAllReports"
  /reports/image:
    $ref: "./routes/report.yaml#/~1getImage"
  /reports/delete/{report_id}:
    $ref: "./routes/report.yaml#/~1deleteById"
  /reports/questionnaire/{report_id}:
    $ref: "./routes/report.yaml#/~1getQuestionnaire"
